import {
  Tv2,
  Music,
  Cloud,
  Gamepad2,
  Newspaper,
  Dumbbell,
  UtensilsCrossed,
  BookOpen,
  Laptop,
  Shirt,
  Sparkles,
  Dog,
  Pill,
  Palette,
  Car,
  Building2,
  Wifi,
  Smartphone,
} from "lucide-react";

export const categories = [
  { label: "Streaming", value: "streaming", icon: Tv2 },
  { label: "Music", value: "music", icon: Music },
  { label: "Cloud", value: "cloud", icon: Cloud },
  { label: "Gaming", value: "gaming", icon: Gamepad2 },
  { label: "News", value: "news", icon: Newspaper },
  { label: "Fitness", value: "fitness", icon: Dumbbell },
  { label: "Meals", value: "meals", icon: UtensilsCrossed },
  { label: "Learning", value: "learning", icon: BookOpen },
  { label: "Software", value: "software", icon: Laptop },
  { label: "Fashion", value: "fashion", icon: Shirt },
  { label: "Beauty", value: "beauty", icon: Sparkles },
  { label: "Pets", value: "pets", icon: Dog },
  { label: "Health", value: "health", icon: Pill },
  { label: "Hobbies", value: "hobbies", icon: Palette },
  { label: "Transit", value: "transit", icon: Car },
  { label: "Finance", value: "finance", icon: Building2 },
  { label: "Internet", value: "internet", icon: Wifi },
  { label: "Mobile", value: "mobile", icon: Smartphone },
] as const;

export type CategoryType = (typeof categories)[number]["value"];
